### ISSUE TITLE
Fullscreen carousel with image description

### ISSUE THREAD

**Issue by robbyceyssens** [dynamicweb/swiffy-slider#10]
I'm trying to use the fullscreen swiffy-slider with image descriptions. I used your example as a starting point but I need to use a bootstrap 5 card inside the li element so it shows the image description below the image:

```
<li class="h-100" tabindex="-1">
<div class="card">
  <img src="../assets/img/photos/img2.webp" class="h-100 w-100 card-img-top" style="object-fit: cover;" loading="lazy" data-bs-dismiss="modal" alt="...">
  <div class="card-body">
    <p class="card-text">This is the image description...</p>
  </div>
</div>
</li>
```

My images are different in size and orientation (landscape/portrait) but I want them to be displayed in the original height/weight (max height/weight if possible but not exceeding the viewport) together with the image description.

How can I do this without getting a scrollbar and content outside of the viewport?

**Comment by nicped** [comment]
I think this is merely an implementation of this particular bootstrap example and not related to the slider it self. I have an open task to work more on that full screen example and this would be a nice addition to that example.
