### ISSUE TITLE
Slider nav "always visible" overlays slider container on touch devices

### ISSUE THREAD

**Issue by hexabinaer** [dynamicweb/swiffy-slider#101]
**Describe the bug**
Select "Always visible" but not "Visible on touch". Use (or emulate) a touch device.

**To Reproduce**
https://swiffyslider.com/configuration/?slider-item-ratio-value=slider-item-ratio-16x9&slider-item-snapping=slider-item-nosnap&slider-nav-dark=slider-nav-dark&slider-nav-arrows=slider-nav-outside&slider-nav-visible=slider-nav-visible&slider-indicators-dark=slider-indicators-dark&slider-indicators-outside=slider-indicators-outside&slider-nav-animation=slider-nav-animation&slider-nav-animation-style=slider-nav-animation-fadein&preview-style=preview-images

**Expected behavior**
Left and right margin should persist

**Suggested amendment**

I think we need another exception for `.slider-nav-visible` in lines 605 and 606:https://github.com/dynamicweb/swiffy-slider/blob/main/src/swiffy-slider.css#L605

 ```
.swiffy-slider:not(.slider-nav-touch, .slider-nav-visible).slider-nav-outside-expand .slider-container,
    .swiffy-slider:not(.slider-nav-touch, .slider-nav-visible).slider-nav-outside .slider-container {
        margin: 0 0rem;
    }
```

**Comment by nicped** [comment]
I am not sure I fully understand. On the above link I do have the arrows on both touch and desktop - is that not what you expect or get?

**Comment by hexabinaer** [comment]
I aplogize for causing confusion :-} I should have rather asked if my assumption was right, thinking

- always visible (excluding touch devices because of the following setting:)
- visible on touch (meaning also on touch devices)

Thus in combination with slider-nav-outside we would expect reserved space left and right of the container.

This assumption was backed by desktop browser emulation of a touch device on Chromium and Firefox

<img alt="screenshot showing an emulated smartphone, arrows visible on top of image" src="https://github.com/user-attachments/assets/fece4488-7725-48b3-84c8-926ed60db9c3" width="300">

I just checked back the above config with a native smartphone (Chromium) and indeed I do not see the arrows there.

Once "visible on touch" is active, it looks all good in every scenario. Seems like a bug in the emulating tools. Sorry.

**Comment by nicped** [comment]
No worries.
I think this is related to the media queries used for the feature. @media (hover: none) is used.
