### ISSUE TITLE
Support for vertical slider

### ISSUE THREAD

**Issue by aimeos** [dynamicweb/swiffy-slider#11]
The current implementation is great for horizontal sliders.
Are there any plans to support vertical sliders too?

**Comment by nicped** [comment]
Not currently - My first thought is that is not a common scenario and I have a hard time understanding the UX issues related to do that. Should be fairly simple to do though - you can maybe even just rotate the .swiffy-slider instance 90 degrees using CSS.

Can you provide a use case for vertical sliders? A design or link to an example?

Thanks for clarifying.

**Comment by aimeos** [comment]
Thank you for your swift response. A common use case is a vertial slider for product image thumbnails:
https://www.amazon.com/BINNUNE-Microphone-Playstation-Headphones-Cancelling/dp/B096VRK6J5/ref=sr_1_1_sspa

Rotating by 90 degrees rotates the images as well, which is undesired.

**Comment by nicped** [comment]
Ok - good case. Will mark it as a request.

You can turn it around like this - first turn the slider, then turn back the slides:

`.swiffy-slider{
    transform: rotate(90deg);
}
.swiffy-slider .slider-container>* {
    transform: rotate(-90deg);
}`

You can then remove the nav buttons from the .swiffy-slider instance and place them outside and customize them.

**Comment by hexabinaer** [comment]
Awesome, thanks for the hint! 

Just to mark another use case: **Digital Signage**. For example, a monitor (kiosk mode, no interaction) displaying upcoming events at a music hall or the next public transport lines expected at a bus stop.

**Comment by nicped** [comment]
Great - good one too! Have not had too much time adding new features to it lately
