### ISSUE TITLE
Multiple Sliders on One page

### ISSUE THREAD

**Issue by Jana993** [dynamicweb/swiffy-slider#12]
Hi! 

Thank you for Swiffy slider - it's super easy to implement and understand. 
I wanted to ask if it's possible to somehow add few sliders on the same page without them having same style/layout ? 
I have tried few times, but it seems that as the classes are the same, any new slider on the page "takes up" the first one's formatting.

**Comment by nicped** [comment]
Hi

Thank you.

Yes, that is possible. Either have different layout on each slide in a slider instance or to have different instances with different design. You can see examples of both on the examples page. https://swiffyslider.com/examples/

Maybe you have an error in your markup? Could be a missing closing tag so classes overflow to the next instance.

BR Nicolai
