### ISSUE TITLE
Left arrow navigate to last slide?

### ISSUE THREAD

**Issue by Blindmikey** [dynamicweb/swiffy-slider#16]
Is there a method to allow the left arrow to navigate to the last slide if we're at the first slide?

**Comment by nicped** [comment]
Yes, of course. Did find it odd my self that loop was only in one direction.
Made a change and released 1.4.0 where loop has changed to be on first and last slide as default. It can then be disabled using slider-nav-noloop which will disable looping all together or by using slider-nav-autohide that will hide navigation arrows on first and last slide.

You can see the new behavior here:
[Looping slides](https://swiffyslider.com/configuration/?slider-item-show=slider-item-show2&slider-item-reveal=slider-item-reveal&slider-nav-visible=slider-nav-visible&preview-style=preview-images)
