### ISSUE TITLE
Readme has outdated link

### ISSUE THREAD

**Issue by Grienauer** [dynamicweb/swiffy-slider#21]
On the bottom of the readme.md file there is a link to [Dynamicweb Swift Ecommerce Starter](https://swiftdemo.dynamicweb-cms.com/)
This link leads to dead end and also the domain dynamicweb-cms.com/ does not resolve to any page and also does not support httpS.

maybe this link is outdated and can be removed.

**Comment by nicped** [comment]
It was just not on https, so fixed that! Thanks for finding.
