### ISSUE TITLE
Example page the first slider example goes crazy after a little bit

### ISSUE THREAD

**Issue by Todd0042** [dynamicweb/swiffy-slider#26]
On https://swiffyslider.com/examples/, once you click start it ends up going crazy for me.  Maybe because it is missing the indicators? 5 slides to 3 indicators?    Just thought I would point it out. It speeds through to the next indicator, and after a couple minutes it was doing even stranger things.

**Comment by nicped** [comment]
Thanks for reporting. Changed the example to be more simple - now it should not go crazy!
