### ISSUE TITLE
Slider-nav-round Next and Previous icons alignment issue at mobile sizes

### ISSUE THREAD

**Issue by nickwelsh1** [dynamicweb/swiffy-slider#27]
**Describe the bug**
When the `slider-nav-round` icons are used, and the browser view is reduced to a mobile size, the background circles are now smaller than the svg icons and don't align perfectly.

**To Reproduce**
1. Go to the examples page https://swiffyslider.com/examples/
2. Reduce the browser view to a mobile size (**less than** 990px wide)
3. Scroll down to the "Articles" example carousel (4th carousel on the examples page)
4. See the next and previous nav icons.

**Expected behavior**
Icons expected to be centered in their background circle. Perhaps the background circle should not be reduced in size on mobile view. Or perhaps the svg icons should also be reduced in size to fit within the circles?

**Screenshots**
![image](https://user-images.githubusercontent.com/15595566/159191597-a0f85604-acbc-4ed9-a189-d3afcbc9ed6f.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome 99, Firefox 98, Vivaldi 5.1.2567.66, Edge 99.0.1150.46 

**Smartphone:**
 - Device: iPhone 11 Pro iOS 14.6 Safari 14 (emulated via Firefox Dev Tools)

**Comment by nicped** [comment]
Thank you for reporting. Made a pull #28 that will fix round and square navigation arrows on mobile and make them a bit larger.

**Comment by nicped** [comment]
Fixed - thanks for reporting
