### ISSUE TITLE
Safari issue with slider buttons on full screen

### ISSUE THREAD

**Issue by bramdupont** [dynamicweb/swiffy-slider#34]
**Describe the bug**
Slider buttons not working on Safari iOS, iPadOS, MacOS,... on fullscreen module.

**To Reproduce**
1. Go to https://swiffyslider.com/examples/
2. Click on the image to open the fullscreen module.
3. Try to click the buttons to go to the next or previous.
4. No response

**Desktop **
 - OS: MacOS 12.3.1
 - Browser Safari
 - Version 15.4

**Smartphone**
 - Device: Iphone 12 Pro
 - OS: iOS 15.4.1
 - Browser: Safari
 - Version: 15.4

**Additional information**
When disabling the CSSOM View Smooth Scrolling, the buttons work again.
Safari>Develop>Experimental features>CSSOM View Smooth Scrolling.

Tried adding the package for smooth scroll polypill, but that doesn't seem to help.

**Comment by nicped** [comment]
Can see that! Must be latest Safari update. Thank you for reporting!

**Comment by richyrb00** [comment]
thanks @nicped for the quick response.
