### ISSUE TITLE
Bare bones version?

### ISSUE THREAD

**Issue by perdittmann** [dynamicweb/swiffy-slider#39]
Is there the possibility to make a "bare bones" version of Swiffy Slider? Or does that not fit into the concept?

I have replaced a couple of old sliders on clients' websites with Swiffy Slider, and for the new slider to fit into the whole design, I had to override quite a bit of the CSS.

I do love the possibility to style the slider just by adding classes, and I am not overly bothered by loading CSS I don't end up using. But it would be great to have a .pure class (or something) that does not style the elements, so I only have to add, not to override.

As I have said before – your slider is a dream come true when I had already given up on looking for something usable and also on trying to write my own. Many, many thanks for this great piece of software – and no less for the stellar support!

**Comment by nicped** [comment]
Thanks - and you are welcome. Same reason we wrote this slider!!

Yeah, I do not think that would be a big issue to do something. Just need to understand which parts that would be - as I see it, the CSS only styles navigation arrows and indicators.
Are you talking about the navigation and indicator styling? Or also their relative position on top of the slides?

**Comment by perdittmann** [comment]
Yes, it's the indicators and the arrows. For one project, I needed to move the indicators to the right side.
.slider-indicators says {justify-content: center;} It was not too hard to change that – but as I said, not having the styles that are already there interfere with my CSS would be a plus. 😁

**Comment by nicped** [comment]
Will look into at some point - should be fairly simple!

**Comment by perdittmann** [comment]
That's great, thank you! Looking forward to it.

**Comment by perdittmann** [comment]
Any news this side of things? The next project is coming up where I could really use this. I know this is not a major issue, but it would be helpful for my workflow. So if the bare bones version should be just around the corner, I'd postpone the project a bit.

**Comment by nicped** [comment]
I am off on vacation very soon and have unfortunately limited time to look into this in the near future… feel free to make a pull - I should be able to look at that when in a boring meeting 😉

**Comment by perdittmann** [comment]
I am happy to hear that! One so busy working on this wonderful piece of software should get all the rest they need.
Okay, I will look into it myself and have a go.

**Comment by tleperou** [comment]
🙌 

In order to avoid overriding styles, as a first step, I wrapped css rules within `:where` (I'm not granted to push those changes @nicped)

If it doesn't opt-out from applying the style, it avoid integrations from using `!important`.

An option could be creating several css files
* default one --> include all styles
* minimum --> in order to get basic features work
* indicators --> add indicators styles
* navigation --> add navigation styles

**Comment by nicped** [comment]
I do like the idea of this - but have not come around to it. There is a relatively large amount of opinionated default styles that could be left out with this - which I like a lot to keep things nice and tidy.

**Comment by tleperou** [comment]
I can push the branch `39-lower-css-specificity` from my local to the remote. And let you give a look if your have time.

The next step could be test against the examples of the doc. Then review code.

Special thanks for your effort, I love the way you tackle the matter 👌

**Comment by nicped** [comment]
I do not know where that branch is - maybe in your own fork? I cannot see it in this repo. On this page on the right panel, you have a section called "Development" where you can create a branch for this subject. So do that, check it out and move your changes to that branch.

**Comment by tobiasbaehr** [comment]
@tleperou You need to fork, then you can create a PR.

You can not push in another repository without you got access for this repository. :D
