### ISSUE TITLE
No loop in Chromium with zoom/scaling

### ISSUE THREAD

**Issue by pneumotube** [dynamicweb/swiffy-slider#43]
The loop stops working when the browser is zoomed out or in (and with _some_ zoom levels it still loops) or when OS is set up to interface scaling. Maybe it has something to do with `grid-auto-columns`.

Applies to at least Chrome, Edge.

**Comment by nicped** [comment]
I cannot reproduce that on the examples pages: [https://swiffyslider.com/examples/](https://swiffyslider.com/examples/).
Tried 110, 125, 150, 200 and 300% zoom

Can you on that page? Using what gear? What zoom?

**Comment by nicped** [comment]
Good catch. That is too weird. For now I will not look into it. Can see it is funny things with changing pixel density virtual screen widths and I am afraid it would require too much JS to fix a rare an not-important issue.

**Comment by pneumotube** [comment]
Okay, no problem. 

Thanks to Swiffy Slider, I went back from custom to 100% UI scaling and enabled animation in the OS :-D
