### ISSUE TITLE
Issues with slider loop

### ISSUE THREAD

**Issue by sonomzy** [dynamicweb/swiffy-slider#45]
Swiffy slider jumps to start or end when loop is activated.
Slides do not actually loop. They just jump.

**Comment by nicped** [comment]
Thank you for joining. Can you ellaborate a bit more?
Are you referring to the infinite example on the doc site example page or in general? Remember that Swiffy slider is a scrolling div and basicslly scrolls back to start or end when looping - that is on purpose and what makes this slider much faster and way smaller than alternatives.

**Comment by sonomzy** [comment]
Oh, all right. It's not a bug if it's a purpose. But the feature will be very much appreciated.

**Comment by nicped** [comment]
There is an infinte example on the examples page you can check out if it fit your needs.

**Comment by sonomzy** [comment]
All right. Thank you.
