### ISSUE TITLE
Incorrect dragging behavior

### ISSUE THREAD

**Issue by katriellucas** [dynamicweb/swiffy-slider#48]
**Describe the bug**
Incorrect behavior when dragging slider on its first and last slide, of course this only happens if you are using the extended version of the lib.

**To Reproduce**
1. Go to 'https://swiffyslider.com/configuration/?slider-nav-mousedrag=slider-nav-mousedrag'
2. On the first image, drag the slider from left to right.
3. You will briefly see the second image on the slider, like we were dragging it from right to left, the reverse also happens if we are on the last image of the slider

**Expected behavior**
Either nothing or the slingshot effect, where you try to drag the slider, but as you release, it returns to its original position.

**Screenshots**
![Recording 2022-07-27 at 00 34 27](https://user-images.githubusercontent.com/54755295/181155219-93fb5b19-32d8-464a-836c-715697559af0.gif)

**Desktop**
 - OS: Windows 11
 - Browser: Brave (Chromium)
 - Version: 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)

**Comment by nicped** [comment]
Good catch. Seems to happen when you drag longer than 1.8x the slide width on first or last slide. So a situation that was not handled by the script.

I have made a small change to take this into consideration.

**Comment by nicped** [comment]
You can test on the examples page - remember to clear your browser cache.
Still needs to be released to NPM - waiting for a verification.
