### ISSUE TITLE
Autoplay don't work on mobile

### ISSUE THREAD

**Issue by Vanlen1er** [dynamicweb/swiffy-slider#57]
**Describe the bug**
The slider work fine on desktop and on the adaptative view on desktop, but on my mobile the autoplay don't work, i see only the first image. (scroll works)

**Smartphone (please complete the following information):**
 - Device: S20fe and iPhone XR
 - OS: iOS 16, android 13
 - Browser: Safari, chrome and firefox

**Additional context**
[www.eliot.fr](www.eliot.fr)

**Comment by nicped** [comment]
I can see that the script does not load at all - and something weird is going on with the script "tarteaucitron" which seems to prevent the script from loading:

![image](https://user-images.githubusercontent.com/3715307/193011430-dd9f5fac-6c4c-4728-a841-0e432f5a6017.png)

Seems to not load - it is not in your document sources.

![image](https://user-images.githubusercontent.com/3715307/193011725-3c5b1441-42c3-4369-bc62-e644cbd8b5a7.png)

To fix this, move the swiffy slider script tag to the header of the site. It is deferred, so you will win nothing from loading it before the body end tag.

**Comment by nicped** [comment]
Ah - I now see your are missing a <script> close tag (</script> or <script src... />):

![image](https://user-images.githubusercontent.com/3715307/193012260-a5dfc953-8c73-4caa-a4e6-388e7142f146.png)

**Comment by nicped** [comment]
Should look like this:
`<script src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider.min.js" crossorigin="anonymous" defer></script>`

**Comment by Vanlen1er** [comment]
Ahhh yes my bad :( sorry for the inconvenience :)
