### ISSUE TITLE
close button for full screen image carousel

### ISSUE THREAD

**Issue by jklue** [dynamicweb/swiffy-slider#6]
I found it hard to close the full screen carousel since there is no close button in the top corner. After I hit "escape" and read the directions though, it made sense.

Add an option to see a close icon in top right to make closing full screen more intuitive. Now, clicking in top right advances to next slide.

If this is an easy addition on my side with scripting, no need to bake into the code.

Thank you! Very clean documentation.

**Comment by nicped** [comment]
Yes, I have actually had the same thought - even though I made it my self!

The full screen is actually just an implementation example (using BS5) and not a part of the slider it self. Also that particular example is also not working well on mobile, so I need to look into it!

Thanks for observing - will update when I have fixed it.

**Comment by lukehatfield** [comment]
I'm sorry I thought the modal was baked in, but makes sense it's not. I found [tingle.js](https://tingle.robinparisi.com/) and combined these two--works a treat!
