### ISSUE TITLE
Random Scrollposition

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [dynamicweb/swiffy-slider#61]
**Describe the bug**
The position of the scrollbar is random and changes upon refresh.

**To Reproduce**
1. Go to https://lautstark-jrk.de/
3. Scroll down to sliders
4. Check scroll positions
5. Refresh to see changing random position

**Expected behavior**
With class _slider-item-snapstart_ the scrollposition should be start, not a random position.

**Screenshots**
![screenshot-lautstark-jrk de-2022 10 11-09_37_12](https://user-images.githubusercontent.com/4689792/195025250-81c5c1b8-12c7-4e18-97a7-b81c537d3be6.png)

https://user-images.githubusercontent.com/4689792/195025647-dde076da-6c94-4aff-8a10-a22d1d7ed787.mp4

**Desktop**
 - OS: Windows
 - Browser: Chrome 
 - Version 106.0.5249.103

**Problem seems not to occur on the following setups**
IOS Safari & Chrome
Windows Firefox

**Comment by nicped** [comment]
Hi

Thank you for using Swiffy Slider.

I can see the issue, but I think it is one of the many plugins you have on the site - there is a lot of DOM manipulation happening after load.

I cannot reproduce the issue in an isolated environment with only the slider script involved - also it behaves as expected with same configuration on the config page: [https://swiffyslider.com/configuration/?slider-item-show=slider-item-show4&slider-item-reveal=slider-item-reveal&slider-item-snapping=slider-item-snapstart&slider-nav-scrollbar=slider-nav-scrollbar](https://swiffyslider.com/configuration/?slider-item-show=slider-item-show4&slider-item-reveal=slider-item-reveal&slider-item-snapping=slider-item-snapstart&slider-nav-scrollbar=slider-nav-scrollbar)

Can you reproduce the issue with no other scripts running on the page, I will be happy to look into it.

BR Nicolai

**Comment by nicped** [comment]
Great! Thanks for letting me know.
Your site looks good by the way!
