### ISSUE TITLE
Download button on https://swiffyslider.com/ does not work

### ISSUE THREAD

**Issue by perdittmann** [dynamicweb/swiffy-slider#62]
When I click on the top right download button on https://swiffyslider.com/ , I get redirected here:
https://github.com/dynamicweb/swiffy-slider/releases/download/v1.6.0/swiffy-slider-1.6.0-dist.zip
There, I am told "Not Found".

This link works: https://github.com/dynamicweb/swiffy-slider/archive/refs/tags/v1.6.0.zip

**Comment by nicped** [comment]
Thanks - now fixed!
