### ISSUE TITLE
Responsiveness for tablet(medium devices)

### ISSUE THREAD

**Issue by Jeet-Pattani** [dynamicweb/swiffy-slider#68]
Swiffy slider is a great library ! No flaws loved the configuration feature provided which eases the development. Just no words for how smoothly it works on mobile. But I found one issue that is there is not option to show less number of slides on tablet devices. I am showing news cards as 5 in desktop and 1 in mobile want to show 3 of them in tablet/Ipad devices but found no option for that. So if possibe please add a feature to customise the number of slides shown on tablet/IPad.

**Comment by nicped** [comment]
Hi
Thank you for using Swiffy Slider! Yes - mobile touch is really nice!

You can add a bit of css in a media query and change the css variable controls the number of slides shown.

#65 - example here.

Br Nicolai
