### ISSUE TITLE
Issue with extension file

### ISSUE THREAD

**Issue by Jeet-Pattani** [dynamicweb/swiffy-slider#70]
The extension files shows some error. I have used it a few days ago it worked fine but is showing up this error from 2 days. 

Uncaught TypeError: Cannot set properties of undefined (setting 'extensions')
    at

Moreover, the mouse dragging feature is also not working. I have tried taking the script running on you website which shows no errors but it does not seem to work.

**Comment by nicped** [comment]
Thanks for giving Swiffy Slider a spin.

Does this one work for you with dragging and do you get any errors using this? [https://swiffyslider.com/configuration/?slider-nav-mousedrag=slider-nav-mousedrag](https://swiffyslider.com/configuration/?slider-nav-mousedrag=slider-nav-mousedrag)

It seems more like an implementation issue, so maybe you can show your code.

**Comment by Jeet-Pattani** [comment]
---------- Forwarded message ---------
From: JEET PATTANI ***@***.***>
Date: Wed, 25 Jan, 2023, 11:30
Subject: Re: [dynamicweb/swiffy-slider] Issue with extension file (Issue
#70)
To: dynamicweb/swiffy-slider <
***@***.***>


Hello Nicolai,

Thank You for always responding so quickly. Below is the code I have used
with the cdn links from the from docs and configuration section. But I
cannot figure out what the error is. The link you sent definitely works but
I don't understand what is the problem here. Below is the error and my
implementation. I have also attached the screen recording of the
implementation please do check it.

Once again thank you so much and have a great day.

**Comment by Jeet-Pattani** [comment]
<img width="433" alt="image (1)" src="https://user-images.githubusercontent.com/93391700/214815194-8c65c547-10e6-4987-b47b-da0fb0c29241.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/93391700/214815200-fc62ecd6-9bd4-4f9b-85cf-92e24135205d.png">




`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider-extensions.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider.min.js" crossorigin="anonymous" defer></script>
    <link href="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/css/swiffy-slider.min.css" rel="stylesheet" crossorigin="anonymous">


</head>
<body>

    <div class="swiffy-slider slider-nav-mousedrag">
        <ul class="slider-container">
            <li><img src="https://source.unsplash.com/49b9l_29ceA/1600x900" style="max-width: 100%;height: auto;"></li>
            <li><img src="https://source.unsplash.com/nKAglN6HBH8/1600x900" style="max-width: 100%;height: auto;"></li>
            <li><img src="https://source.unsplash.com/E9ZwWcMGzj8/1600x900" style="max-width: 100%;height: auto;"></li>
        </ul>
    
        <button type="button" class="slider-nav"></button>
        <button type="button" class="slider-nav slider-nav-next"></button>
    
        <div class="slider-indicators">
            <button class="active"></button>
            <button></button>
            <button></button>
        </div>
    </div>

</body>
</html>`

**Comment by nicped** [comment]
It is the loading order of your scripts - load extensions after swiffy-slider it self:

```
<script src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider.min.js" crossorigin="anonymous" defer></script>
<script src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider-extensions.min.js"></script>
```
