### ISSUE TITLE
Looping not working

### ISSUE THREAD

**Issue by dhawal24** [dynamicweb/swiffy-slider#72]
Hi,

Looping from right arrow is not working.

**Comment by nicped** [comment]
Yes it is,

**Comment by dhawal24** [comment]
I have used multiple slider in one page & some slider are under tabs, also I haven't used the class no-loop on any of the slider.

But the loop are not working on any slider. Also when I have ratio class the loop starts working but shows scrollbar on right side.

**Comment by nicped** [comment]
What if you test on https://swiffyslider.com/ - do the loop work? It does for me.

My guess is that you have some kind of implementation detail that is causing the issue. If you need help to figure out what it is, you can provide a link to the page where the error occurs, or provide a codepen with the issue so I can take look.

**Comment by tobiasbaehr** [comment]
In our case the option "No snap" or class `slider-item-nosnap` works. default is center.

**Comment by tobiasbaehr** [comment]
@nicped yes more a edge case and workaround. :D Try the slider with `slider-item-show2`  https://www.openculturas.org/de/referenzen. No problems with `slider-item-show3` .

**Comment by nicped** [comment]
Maybe there is something I do not understand :-).
If I try the slider on that page (nice by the way!) using `slider-item-show2` or `slider-item-show3 `or just has you have set it up, it works as expected for me...
Or could it be a Safari on Apple device that is the issue?

**Comment by tobiasbaehr** [comment]
Firefox/manjaro. ;-)

The next button/indicators works then not anymore.

We know it has something to do with css/html, because we just change the theme, where it works, but we do not know whats problem with the css. but atm we can live with no-snap. :D

fyi: https://www.drupal.org/project/swiffy_slider

**Comment by nicped** [comment]
Looking further into this, I think Firefox have fixed the issue - so my fix is now causing the issue.

A quick local test shows me that if I completely remove these lines:
[https://github.com/dynamicweb/swiffy-slider/blob/main/src/swiffy-slider.css#L479-L491](https://github.com/dynamicweb/swiffy-slider/blob/main/src/swiffy-slider.css#L479-L491)

All works like a charm...

**Comment by hexabinaer** [comment]
Thank you nicped for taking the time to inspect the issue, really appreciate it. 

Our team loves Swiffy Slider and I'm positive it can overhaul most of the "established" slider solutions that have been provided for Drupal so far.

**Comment by hexabinaer** [comment]
> A quick local test shows me that if I completely remove these lines: https://github.com/dynamicweb/swiffy-slider/blob/main/src/swiffy-slider.css#L479-L491

Makes sense. 

I tried removing those lines but unfortunately this does not fix the issue in our setup. 

![screenshot: 2 logos in a slider](https://user-images.githubusercontent.com/1636619/227003404-bd00af21-fec3-4f9e-a1f2-e6a56c6bb348.png)
This is the initial state on page load with 2 items and "Snap center": Active indicator is on last slide and neither navigation button works.

I'll look into the :before pixel widths, thanks for that hint.

**Comment by dhawal24** [comment]
The issue is resolve & working for me
