### ISSUE TITLE
Div Wrapper under slider-container 

### ISSUE THREAD

**Issue by dhawal24** [dynamicweb/swiffy-slider#78]
Hi,

I am using Swiffy slider for one of my CMS project & due to structure issue there is dynamic div rendering after slider-container & because of this the slider is not working.

Below is dummy code:
div class="swiffy-slider"
  div class="slider-container"
     div class="dynamicDiv"
         div class="slide1" /div
         div class="slide2" /div
         div class="slide3" /div
     /div
 /div
/div

**Comment by nicped** [comment]
Well - that is not a Swiffy Slider issue - you need to solve that in your markup. The structure has to follow

`swiffy-slider -> slider-container -> slide`
