### ISSUE TITLE
Hide left arrow on load

### ISSUE THREAD

**Issue by lukehatfield** [dynamicweb/swiffy-slider#8]
I'm being nit-picky, but when I enable arrows, I'm seeing one on the left on initial load. It doesn't do anything, and I don't want it to. Wondering if it could just be hidden until the user clicks right one time. 

Is this something I should implement on my end?

![image](https://user-images.githubusercontent.com/5399943/148573188-aa2758ce-d1d4-41c3-b7e2-2ccc923ed45c.png)

**Comment by nicped** [comment]
It is ok to be nit-picky - I have given this particular issue some thoughts in the process. It would be easy to remove using js, but I also want it all to be very simple. But I am sure I can come up with a lightweight solution to this.

**Comment by nicped** [comment]
It could also go to last slide when you slide left on first slide...?

**Comment by nicped** [comment]
This feature has been added.

You can add slider-nav-autohide to the `swiffy-slider` instance and that is enough. When the JS loads, it will detect which slides are visible and set `slider-item-first-visible` or `slider-item-last-visible` classes on the `swiffy-slider` instance.

If you know that the first item is visible on initial load (usually will be), always apply `slider-item-first-visible` to avoid CLS and flickering.

```
<div class="swiffy-slider slider-nav-visible slider-nav-autohide slider-item-first-visible">
    <ul class="slider-container">
        <li>...</li>
    </ul>

    <button type="button" class="slider-nav"></button>
    <button type="button" class="slider-nav slider-nav-next"></button>
</div>
```

See an example in the configurator:
https://swiffyslider.com/configuration/?slider-nav-visible=slider-nav-visible&slider-nav-autohide=slider-nav-autohide&slider-item-first-visible=slider-item-first-visible
