### ISSUE TITLE
Lazy Loading Images

### ISSUE THREAD

**Issue by staycreativedesign** [dynamicweb/swiffy-slider#80]
How does one go about lazy loading images?

**Comment by nicped** [comment]
It is in the documentation. If you see the code in examples: [https://swiffyslider.com/examples/](https://swiffyslider.com/examples/)

The examples simply uses loading=lazy which has more or less full browser support - so it is not a Swiffy Slider feature - just a browser feature and it works great.

Do not compare to all the all-style weird custom build js loading things in other older slider components
