### ISSUE TITLE
A few beginner questions

### ISSUE THREAD

**Issue by drenina** [dynamicweb/swiffy-slider#82]
I am new to this slider. I have a few questions (and one bug):

- how can I change the slide gap? In the configurator, there is no option unfortunately...
- when I choose the reveal effect, how can I also have this effect for the first slide, so that you see part of an image on the left as well?
- how can I have the carousel alsways slide from right to left, even after the last slide it should slide to the left to the first image/slide. 

And the bug: I am using Fennec broser on Android, and even the demos are buggy- The navigation arrows and dots aren't displayed correctly and the swiping is buggy, too.

Thank you!

**Comment by nicped** [comment]
Hi

- To change the slide gap, you can set the --swiffy-slider-item-gap variable - see "Css variables" section on this page: https://swiffyslider.com/docs/
- It is not possible to show the reveal to the left for the first slide. Slides do not 'circle' around so the last slide is not before the first slide in this context. The best option is to slide to slide 2 on load so it looks like it has something on the left. - on page load do `swiffyslider.slideTo(document.getElementById('myslider'), 1);` But the best option is to just leave it as is - it makes it easier for a user to 
- There is an example of how to do that here: [https://swiffyslider.com/examples/#infinite](https://swiffyslider.com/examples/#infinite). I would suggest not to do it as it helps users to understand when they have seen the first and the last slide. Infinite sliding in most cases makes it confusing for the user to find out when they have seen all.

**Comment by drenina** [comment]
@nicped thank you. But what about the bug on mobile? Even the demos aren't displayed correctly and buggy.
