### ISSUE TITLE
NPM/Yarn import not working with React

### ISSUE THREAD

**Issue by sasham43** [dynamicweb/swiffy-slider#9]
**Describe the bug**
When attempting to import swiffyslider into a React project, I get `Module not found: Can't resolve 'swiffy-slider'`.

**To Reproduce**
1. Run `yarn add swiffy-slider` in fresh project.
2. Create `index.js` with `import swiffyslider from 'swiffy-slider`
3. Run `node index.js`

**Expected behavior**
The swiffyslider object is imported into the file, and I can use it.

**Additional context**
In attempting to debug this issue, I think part of it has to do with the package.json (it has `"main": "dist/swiffy-slider.ESM.min.js"` when I think it should be `"main": "dist/js/swiffy-slider-ESM.min.js"`).  I think there might be an issue with ES6 Module Syntax vs CommonJS syntax.

**Comment by nicped** [comment]
Yes, it is because the src folder is missing from the npm package. Will fix this and at the same time make the package esm compatible as well. Thanks for observing.

**Comment by sasham43** [comment]
Ah okay!  Thanks for the quick response!

**Comment by nicped** [comment]
Should be foxed wit 1.3 release! Thanks again.
