### ISSUE TITLE
Looping end to start not working on Webkit Browsers

### ISSUE THREAD

**Issue by kurtjmeyoung** [dynamicweb/swiffy-slider#92]
**Describe the bug**
Currently the infinite loop does not work to go back from last slide to the first slide. However it is working the other way around, from first slide to last slide. It seems this is only a problem on Webkit based browsers. It doesn't work on Chrome, Edge, Brave but does work on Firefox.

**To Reproduce**
1. You can simply test it on the configuration page: https://swiffyslider.com/configuration/

**Expected behavior**
The infinite loop should also work on Webkit based browsers.

**Desktop (please complete the following information):**
 - Windows 11
 - Browser: Chrome 123, Edge  123, Brave 1.64.113

**Smartphone (please complete the following information):**
 - Not tested

**Comment by GarrettL** [comment]
Having the same issue as well

**Comment by nicped** [comment]
I cannot reproduce in any webkit browsers in any viewports...
https://github.com/dynamicweb/swiffy-slider/assets/3715307/a35bd7fd-16db-40bf-82ac-562a7d58cfc3

Can you show me an example?

**Comment by kurtjmeyoung** [comment]
I also can't reproduce it anymore now. It is now working for me both on [https://swiffyslider.com/configuration/](https://swiffyslider.com/configuration/) as well as on my own page. Don't know what happened. Maybe something has changed on the chrome side of things?

**Comment by nicped** [comment]
Maybe... There have been some very very very specific issues with precise viewport widths - +/- 1px that could cause this, mostly seen in FF though. It could be a change related to that in recent updates.

I have also seen this when Swiffyslider is being inserted into an implementation where the containing dom element is not sizing 'correct' and confuses the scroll position.
